### ISSUE TITLE
How to add to .swcrc

### ISSUE THREAD

**Issue by yvuong** [ankitchouhan1020/swc-plugin-transform-import#3]
Not an issue but a question.  I'm currently using @swc/register to transpile on the fly for local development.  How do I add this plugin to the .swcrc config file? Or would I somehow add it as an option to @swc/register? Thanks.

**Comment by ankitchouhan1020** [comment]
Currently, there is no way to add this plugin to .swrcrc.
https://github.com/swc-project/swc/issues/1321
Folks are working on adding string plugins for now. Function plugins will take more time to implement.

**Comment by havenchyk** [comment]
@ankitchouhan1020 but how do you use this plugin if it's not possible to include it into `swc/jest` for example? Only in webpack configuration?

**Comment by ankitchouhan1020** [comment]
@havenchyk Just checked swc-project/jest repo, they are using the transformSync function. I have used the same function to test this plugin.

```js
// jest.config.js
module.exports = {
  plugin: (m) => new PluginTransformImport({
                "lodash": {
                  "transform": "lodash/${member}",
                  "preventFullImport": true
                }
              }).visitProgram(m),
}
```

So this might work since they are just spreading the jestOptions to transformSync function.
I haven't tested it yet.

**Comment by havenchyk** [comment]
got it, I tried the same, probably custom transform can be used. Thanks!

**Comment by yvuong** [comment]
> Currently, there is no way to add this plugin to .swrcrc. [swc-project/swc#1321](https://github.com/swc-project/swc/issues/1321) Folks are working on adding string plugins for now. Function plugins will take more time to implement.

Is there an example somewhere of a string plugin and of how to use it outside of the webpack.config?  I'm still very new to this and am looking for anyway I can use this plugin or any JS plugin with @swc/register.

**Comment by havenchyk** [comment]
@yvuong please check this https://github.com/swc-project/swc/issues/1253#issuecomment-1083570870 might be helpful

**Comment by yvuong** [comment]
> @yvuong please check this [swc-project/swc#1253 (comment)](https://github.com/swc-project/swc/issues/1253#issuecomment-1083570870) might be helpful

@havenchyk thanks for the link, but from what I understood, the experimental plugin configuration in .swcrc was only for the new Rust based plug-in system and not the JS plugins.  Am I mistaken?

**Comment by hugufc** [comment]
@yvuong I think you are right. 

Even so, you probably need to check [this](https://twitter.com/kdy1dev/status/1509536470394019847?s=20&t=8CxkBTnzSbhabid5i46kzQ). A Rust based [tranform-import](https://github.com/swc-project/plugins/tree/main/packages/transform-imports) plugin was published recently.
